#!/bin/sh

# shellcheck disable=SC2034,SC2006
path=`pwd`
delete='uninstall'
otl_run="${HOME}/.otl/run-tool/bin/otl"

if [ -z "$1" ]; then
    $otl_run -classpath "${HOME}"/.otl/analyzer Main "${path}"
    exit 0
else
  # shellcheck disable=SC2039,SC2081,SC2016
  if [ "${1}" == "${delete}" ]; then
      if [ "${OSTYPE}" == "linux-gnu"* ]; then
          sed -i '' '/alias otl="sh ${HOME}/d' ~/.bashrc; rm -rf .otl
          echo "삭제가 완료되었습니다."
      elif [ "${OSTYPE}" == "darwin"* ]; then
          sed -i '' '/alias otl="sh ${HOME}/d' ~/.zshrc; rm -rf .otl
          echo "삭제가 완료되었습니다."
      else
          echo "지원하지 않는 OS 입니다."
      fi
  else
      $otl_run -classpath "${HOME}"/.otl/analyzer Main "${path}" "$1"
  fi
fi